### ISSUE TITLE
Blender for Mac

### ISSUE THREAD

**Issue by GeorgPopp** [jesterKing/import_3dm#95] opened 2022-03-07 17:55 UTC
Hi there, 

Does the Plug-In also run for Blender on macOS?
I cannot get it to work. 

Best, 
Georg

**Comment by jesterKing** [comment] 2022-03-21 07:29
It works on Intel MacOS, but not yet on Apple Silicon. I'm waiting for proper builds of the module `rhino3dm`.

**Comment by jesterKing** [comment] 2022-03-21 07:30
Duplicate of #89

**Closed by jesterKing** 2022-03-21 07:30 UTC

**Comment by jesterKing** [comment] 2022-03-21 07:40
FWIW using the Intel binary on M1 works fine even in Blender 3.2 alpha builds

Here I imported a house I modeled in Rhino 7

<img width="1055" alt="kuva" src="https://user-images.githubusercontent.com/87916/159220768-42d98592-533f-42dc-b91d-41665a880b15.png">
